apiVersion: v1
kind: PersistentVolume
metadata:
  name: runboat-pv-001
spec:
  storageClassName: do-block-storage
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/"
