apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runboat-pvc-001
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 200Mi
    limits:
      storage: 250Mi
